apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-counter
  name: python-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-counter
  strategy: {}
  template:
    metadata:
      labels:
        app: python-counter
    spec:
      containers:
      - image: acrwekubernetesavanzado.azurecr.io/python-counter:1.4.0
        name: counter
        resources: {}
